 import AppNavigation from "@/components/AppNavigation";
 import AppFooter from "@/components/AppFooter";
import './globals.css';
 export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* You can include meta tags, fonts, or other head elements here */}
      </head>
      <body className="font-sans bg-gray-50">
        {/* Navbar */}
        <header className="bg-blue-600 text-white p-4">
          <AppNavigation/>
        </header>

        {/* Main Content */}
        <main className="flex-grow p-4">{children}</main>

        {/* Footer */}
        <footer className="bg-gray-800 text-white p-4 text-center">
          <AppFooter/>
        </footer>
      </body>
    </html>
  );
}
