import AppNavigation from "@/components/custom/AppNavigation";
import AppFooter from "@/components/custom/AppFooter";
import './globals.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* You can include meta tags, fonts, or other head elements here */}
      </head>
      <body className="font-sans flex flex-col min-h-screen">
        {/* Navbar */}
        <header className=" p-4">
          <AppNavigation/>
        </header>

        {/* Main Content */}
        <main className="flex-grow bg-white">{children}</main>

        {/* Footer */}
        <footer className="text-white p-4 text-center">
          <AppFooter/>
        </footer>
      </body>
    </html>
  );
}
